### ISSUE TITLE
Implement Config.js for API Key Management and Update Codebase

### ISSUE THREAD

**Issue by Vaibhav260** [ncsuswe24/units_converter_extension#15]
## Describe the solution you'd like

- **Implement Config.js for API Key Configuration**: Introduce a `Config.js` file in the root directory to store the API key required for currency conversion using the exchangerate.host API. This file should be excluded from version control to protect the API key.

- **Provide Config.js.example**: Add a `Config.js.example` file to serve as a template for users. It should include instructions or placeholders indicating where to insert their own API key.

- **Refactor Code to Use Config.js**: Update the codebase to reference the API key from `Config.js` instead of having it hardcoded. This includes:
  - Removing the hardcoded API key from `Currency.js`.
  - Adjusting `popup.html` to include `Config.js` before other scripts that depend on it.
  - Ensuring that `Currency.js` and any other scripts access `API_KEY` from the global scope.

- **Update Documentation**: Modify the existing documentation to include concise instructions on how to:
  - Obtain a free API key from [exchangerate.host](https://exchangerate.host/).
  - Create their own `Config.js` by copying `Config.js.example` and inserting their API key.
  - Ensure that `Config.js` is not committed to the repository.

- **Add Config.js to .gitignore**: Ensure that `Config.js` is listed in the `.gitignore` file to prevent accidental commits of sensitive information.

## Additional context

Currently, the API key is hardcoded within `Currency.js`, which poses security risks and hinders collaboration:

- **Security Risks**: Exposing the API key in the repository can lead to unauthorized usage and potential exhaustion of API limits.

- **Onboarding Challenges**: New developers may face difficulties setting up the project without clear instructions for configuring the API key.

By implementing `Config.js` and updating the codebase:

- **Enhanced Security**: API keys remain confidential and are not exposed in the codebase.

- **Improved Developer Experience**: Clear instructions and templates help new contributors set up the project effortlessly.

- **Best Practices Compliance**: Aligns the project with common practices for handling sensitive configuration data.

**Tasks Involved**:

1. **Create `Config.js.example`**:
   - Provide a template with instructions for inserting the API key.

2. **Update `.gitignore`**:
   - Add `Config.js` to prevent it from being tracked by Git.

3. **Refactor `Currency.js`**:
   - Remove the hardcoded API key.
   - Access `API_KEY` from the global scope defined in `Config.js`.

4. **Adjust `popup.html`**:
   - Include `Config.js` before other scripts that depend on `API_KEY`.

5. **Update Documentation**:
   - Add a section detailing how to obtain an API key and set up `Config.js`.

6. **Test Changes**:
   - Verify that currency conversion features work after the refactoring.

---

By addressing this issue, we'll enhance the security of the project and make it more accessible to contributors.

---

**Comment by MiaAmeen** [comment]
Resolved by PR #16
